package com.teamtwothree.kartasvalokapp.service

import androidx.lifecycle.LiveData
import com.teamtwothree.kartasvalokapp.model.point.PointDetails
import com.teamtwothree.kartasvalokapp.model.report.Report
import com.teamtwothree.kartasvalokapp.model.user.UserInfo
import retrofit2.Call

/**
 * Basic Service for server API interaction and storing user info.
 * Obtain an instance in a field of your class via
 * <code> private val dataService: DataService by kodein.instance() </code>
 */
interface DataService {
    /**
     * Fetches [PointDetails] info from server API and saves to local DB
     * @param id String with id of requested point
     * @return [PointDetails] from updated DB
     */
    fun getPointDetails(id: String): LiveData<PointDetails>
    /**
     * Fetches all reports that were previously sent from app and saved into local db.
     * @return List<[PointDetails]> containing all reports
     */
    fun getAllPointDetails(): LiveData<List<PointDetails>>
    /**
     * Posts Report to server API and saves result in DB.
     * @param report [Report] to be posted
     * @return String with Id, generated by the server or null if posting failed
     */
    fun postReport(report: Report): LiveData<String>
    /**
     * Fetches User information stored in a local db
     * @return [UserInfo] from local DB
     */
    fun getUserInfo(): LiveData<UserInfo>
    /**
     * Stores [UserInfo] in local db
     * @param userInfo [UserInfo] to store
     */
    fun saveUserInfo(userInfo: UserInfo)
    /**
     * TESTING implementation: Method for Test Server only. Flushes current remote db
     */
    fun flushPoints(): Call<Void>

    fun getUserInfoBlocking(): UserInfo
}
